name: Build Passwall2 Suite (x86-64)

on:
  #schedule:
  #    - cron: '0 22 * * *'   # 每天 UTC 22:00 = 北京时间次日 06:00
  workflow_dispatch:
    inputs:
      passwall2_ref:
        description: 'passwall2 commit/branch/tag to build (default: main)'
        required: false
        default: 'main'

jobs:
  build-passwall2-suite:
    runs-on: ubuntu-22.04

    env:
      OPENWRT_VERSION: 24.10.3
      TARGET_DIR: x86/64
      ARCH_DIR: x86_64
      SDK_DIRNAME: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64
      SDK_ARCHIVE: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    steps:
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget zstd

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET_DIR}/${SDK_ARCHIVE}
          tar --use-compress-program=unzstd -xf ${SDK_ARCHIVE}
          mv ${SDK_DIRNAME} openwrt-sdk

      - name: Fetch passwall2 source
        run: |
          git clone https://github.com/xiaorouji/openwrt-passwall2.git src-passwall2
          cd src-passwall2
          git checkout "${{ github.event.inputs.passwall2_ref }}"

      - name: Place passwall2 package into SDK
        run: |
          # passwall2 仓库包含多个 package 和 luci-app-passwall2
          cp -r src-passwall2 openwrt-sdk/package/passwall2

      - name: Update feeds and defconfig
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build passwall2 and dependencies
        working-directory: openwrt-sdk
        run: |
          # 编译 passwall2 及其依赖
          make package/passwall2/compile | tee build-passwall2.log
          make package/luci-app-passwall2/compile | tee -a build-passwall2.log

      - name: Collect built packages
        id: collect
        working-directory: openwrt-sdk
        run: |
          mkdir -p ../release-ipks
          # 收集 passwall2 相关的所有 ipk
          find bin/packages/${ARCH_DIR} -type f -name 'passwall2*.ipk' -exec cp {} ../release-ipks/ \;
          find bin/packages/${ARCH_DIR} -type f -name 'luci-app-passwall2*.ipk' -exec cp {} ../release-ipks/ \;
          find bin/packages/${ARCH_DIR} -type f -name 'luci-i18n-passwall2-*.ipk' -exec cp {} ../release-ipks/ \;
          echo "release_tag=passwall2-${{ env.OPENWRT_VERSION }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt-sdk/build-passwall2.log

      - name: Upload artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: passwall2-x86_64-ipk
          path: release-ipks/*.ipk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.collect.outputs.release_tag }}
          name: Passwall2 Suite for OpenWrt ${{ env.OPENWRT_VERSION }} (${{ github.sha }})
          draft: false
          prerelease: false
          files: release-ipks/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
