name: Build ImmortalWrt Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git wget unzip \
            file libssl-dev python3 zstd qemu-utils genisoimage grub2

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
          tar -I zstd -xf immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
          mv immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64 imagebuilder

      - name: Prepare custom files
        run: |
          mkdir -p imagebuilder/files/etc/uci-defaults
          cp uci-custom imagebuilder/files/etc/uci-defaults/99-custom-network
          mkdir -p imagebuilder/packages
          cp packages/*.ipk imagebuilder/packages/ || true

      - name: Configure ROOTFS partition size
        working-directory: imagebuilder
        run: |
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=1024" >> .config
          make defconfig

      - name: Build firmware
        working-directory: imagebuilder
        run: |
          PKGS=$(tr '\n' ' ' < ../packages.list)
          make image \
            PACKAGES="$PKGS" \
            FILES="files"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: imagebuilder/bin/targets/x86/64/*

      - name: Generate tag name
        id: tag
        run: |
          DATE=$(date +'%Y%m%d')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=auto-${DATE}-${SHORT_SHA}" >> $GITHUB_ENV
          echo "Generated tag: auto-${DATE}-${SHORT_SHA}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "ImmortalWrt Firmware ${{ env.TAG }}"
          draft: false
          prerelease: false
          files: imagebuilder/bin/targets/x86/64/*
