name: Build & Release ImmortalWrt x86_64

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "额外需要包含的包 (空格分隔)"
        required: false
        default: ""
      profile:
        description: "ImageBuilder PROFILE (x86-64 默认 generic)"
        required: false
        default: "generic"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGEBUILDER_URL: https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
      FILES_DIR: files
      LOCAL_IPK_DIR: packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential make curl ca-certificates zstd xz-utils coreutils \
            qemu-utils genisoimage grub2 dosfstools e2fsprogs gzip tzdata jq

      - name: Prepare files & ensure uci-defaults executable
        run: |
          mkdir -p ${FILES_DIR}/etc/uci-defaults ${LOCAL_IPK_DIR}
          [ -f packages.txt ] || touch packages.txt
          
          # 确保uci-defaults目录存在且脚本可执行
          echo "检查文件结构:"
          find ${FILES_DIR} -type f 2>/dev/null | sort || echo "无自定义文件"
          
          # 设置uci-defaults目录中所有脚本为可执行
          if [ -d "${FILES_DIR}/etc/uci-defaults" ]; then
            echo "设置uci-defaults脚本权限:"
            find "${FILES_DIR}/etc/uci-defaults" -type f -name "*.sh" -exec chmod +x {} \;
            echo "脚本列表:"
            ls -la ${FILES_DIR}/etc/uci-defaults/ 2>/dev/null || echo "uci-defaults目录为空"
          else
            echo "警告: ${FILES_DIR}/etc/uci-defaults 目录不存在"
            # 创建目录并添加一个示例脚本（可选）
            mkdir -p ${FILES_DIR}/etc/uci-defaults
          fi
          
          # 验证99-custom.sh是否存在且可执行
          if [ -f "${FILES_DIR}/etc/uci-defaults/99-custom.sh" ]; then
            chmod +x "${FILES_DIR}/etc/uci-defaults/99-custom.sh"
            echo "99-custom.sh 权限设置成功:"
            ls -la "${FILES_DIR}/etc/uci-defaults/99-custom.sh"
            echo "脚本内容预览(前10行):"
            head -10 "${FILES_DIR}/etc/uci-defaults/99-custom.sh"
          else
            echo "错误: ${FILES_DIR}/etc/uci-defaults/99-custom.sh 文件不存在!"
            echo "请确保仓库中有 files/etc/uci-defaults/99-custom.sh 文件"
           
      - name: Download ImageBuilder
        run: |
          curl -L "$IMAGEBUILDER_URL" -o imagebuilder.tar.zst
          mkdir -p imagebuilder
          tar --use-compress-program=unzstd -xf imagebuilder.tar.zst -C imagebuilder

      - name: Locate ImageBuilder
        id: ib
        run: |
          IB_DIR="$(find imagebuilder -maxdepth 1 -type d -name 'immortalwrt-imagebuilder-*' | head -n1)"
          if [ -z "$IB_DIR" ]; then
            echo "错误: 未找到ImageBuilder目录"
            exit 1
          fi
          echo "ib_dir=${IB_DIR}" >> "$GITHUB_OUTPUT"
          echo "找到ImageBuilder目录: ${IB_DIR}"

      - name: Merge package list
        id: pkgs
        run: |
          TXT_PACKAGES="$(grep -v '^\s*#' packages.txt | sed '/^\s*$/d' | xargs || true)"
          INPUT_PACKAGES="${{ github.event.inputs.packages }}"
          MERGED="$(printf '%s %s\n' "$TXT_PACKAGES" "$INPUT_PACKAGES" | xargs || true)"
          echo "merged=${MERGED}" >> "$GITHUB_OUTPUT"
          echo "Packages: $MERGED"

      - name: Verify build environment
        run: |
          echo "=== 构建环境验证 ==="
          echo "ImageBuilder目录: ${{ steps.ib.outputs.ib_dir }}"
          echo "文件目录结构:"
          find ${FILES_DIR} -type f 2>/dev/null | sort || echo "无自定义文件"
          
          echo "uci-defaults目录内容:"
          ls -la ${FILES_DIR}/etc/uci-defaults/ 2>/dev/null || echo "目录不存在"
          
          if [ -f "${FILES_DIR}/etc/uci-defaults/99-custom.sh" ]; then
            echo "99-custom.sh 验证:"
            ls -la "${FILES_DIR}/etc/uci-defaults/99-custom.sh"
            echo "文件类型:"
            file "${FILES_DIR}/etc/uci-defaults/99-custom.sh"
          fi

      - name: Build firmware
        run: |
          IB_DIR="${{ steps.ib.outputs.ib_dir }}"
          cd "$IB_DIR"

          # 强制写入 RootFS 分区大小
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=1024" >> .config

          EXTRA_REPO_DIRS=""
          if [ -n "$(ls -A "../${LOCAL_IPK_DIR}" 2>/dev/null || true)" ]; then
            EXTRA_REPO_DIRS="../${LOCAL_IPK_DIR}"
          fi

          # 显示构建参数用于调试
          echo "=== 构建参数 ==="
          echo "PROFILE: ${{ github.event.inputs.profile }}"
          echo "PACKAGES: ${{ steps.pkgs.outputs.merged }}"
          echo "FILES: ../${FILES_DIR}"
          echo "REPO_DIRS: ${EXTRA_REPO_DIRS}"
          
          # 验证FILES目录是否存在
          echo "检查FILES目录:"
          ls -la "../${FILES_DIR}" || echo "FILES目录不存在"
          
          # 执行构建
          make -j"$(nproc)" image \
            PROFILE="${{ github.event.inputs.profile }}" \
            PACKAGES="${{ steps.pkgs.outputs.merged }}" \
            FILES="../${FILES_DIR}" \
            ${EXTRA_REPO_DIRS:+REPO_DIRS="$EXTRA_REPO_DIRS"}

          echo "=== 构建输出 ==="
          ls -lh bin/targets/x86/64/

      - name: Generate SHA256 checksums
        run: |
          cd imagebuilder/immortalwrt-imagebuilder-*/bin/targets/x86/64/
          sha256sum * > sha256sums.txt
          echo "生成的SHA256校验和:"
          cat sha256sums.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-x86_64-images
          path: imagebuilder/immortalwrt-imagebuilder-*/bin/targets/x86/64/**

      - name: Generate release notes
        id: notes
        run: |
          BUILD_TIME="$(date '+%Y-%m-%d %H:%M:%S %Z')"
          BUILD_DATE="$(date '+%Y-%m-%d')"
          echo "build_time=${BUILD_TIME}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

          echo "### Build Information" > release_notes.md
          echo "- **Build Time**: ${BUILD_TIME}" >> release_notes.md
          echo "- **Profile**: ${{ github.event.inputs.profile }}" >> release_notes.md
          echo "- **RootFS Size**: 1024 MB" >> release_notes.md
          echo "- **首次启动脚本**: files/etc/uci-defaults/99-custom.sh" >> release_notes.md
          echo "- **Packages**:" >> release_notes.md
          if [ -s packages.txt ]; then
            sed 's/^/- /' packages.txt >> release_notes.md
          fi
          if [ -n "${{ steps.pkgs.outputs.merged }}" ]; then
            echo "- Extra: ${{ steps.pkgs.outputs.merged }}" >> release_notes.md
          fi
          echo "" >> release_notes.md
          echo "### SHA256 Checksums" >> release_notes.md
          cat imagebuilder/immortalwrt-imagebuilder-*/bin/targets/x86/64/sha256sums.txt >> release_notes.md

          echo "release_notes_path=release_notes.md" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ steps.notes.outputs.build_date }}"
          name: "ImmortalWrt Build ${{ steps.notes.outputs.build_date }} (RootFS=1024M)"
          draft: false
          prerelease: false
          body_path: ${{ steps.notes.outputs.release_notes_path }}
          files: imagebuilder/immortalwrt-imagebuilder-*/bin/targets/x86/64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
