name: Build OpenClash (x86-64, minimal)

on:
  workflow_dispatch:

jobs:
  build-openclash:
    runs-on: ubuntu-22.04

    env:
      OPENWRT_VERSION: 24.10.3
      TARGET_DIR: x86/64
      ARCH_DIR: x86_64
      SDK_DIRNAME: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64
      SDK_ARCHIVE: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    steps:
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget zstd golang curl upx

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET_DIR}/${SDK_ARCHIVE}
          tar --use-compress-program=unzstd -xf ${SDK_ARCHIVE}
          mv ${SDK_DIRNAME} openwrt-sdk

      - name: Add OpenClash feed
        working-directory: openwrt-sdk
        run: |
          echo "src-git openclash https://github.com/vernesong/OpenClash.git;master" >> feeds.conf.default

      - name: Update feeds and defconfig
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build OpenClash
        working-directory: openwrt-sdk
        run: |
          make package/luci-app-openclash/compile V=s | tee build-openclash.log

      - name: Debug package output
        working-directory: openwrt-sdk
        run: |
          echo "=== Built IPKs ==="
          find bin/packages -type f -name '*.ipk'

      - name: Collect built packages
        id: collect
        working-directory: openwrt-sdk
        run: |
          mkdir -p ../release-ipks
          find bin/packages -type f -name 'luci-app-openclash*.ipk' -exec cp {} ../release-ipks/ \;
          find bin/packages -type f -name 'luci-i18n-openclash-zh-cn*.ipk' -exec cp {} ../release-ipks/ \;
          echo "release_tag=openclash-${{ env.OPENWRT_VERSION }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt-sdk/build-openclash.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openclash-x86_64-ipk
          path: release-ipks/*.ipk
