name: Build DDNS-Go Suite (x86-64)

on:
  schedule:
    - cron: '0 7 * * *'  # 07:00 UTC daily
  workflow_dispatch:
    inputs:
      luci_ref:
        description: 'luci commit/branch/tag to build (default: master)'
        required: false
        default: 'master'
      packages_ref:
        description: 'packages commit/branch/tag to build (default: master)'
        required: false
        default: 'master'

jobs:
  build-ddnsgo-suite:
    runs-on: ubuntu-22.04

    env:
      OPENWRT_VERSION: 24.10.3
      TARGET_DIR: x86/64
      ARCH_DIR: x86_64
      SDK_DIRNAME: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64
      SDK_ARCHIVE: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    steps:
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget zstd golang

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET_DIR}/${SDK_ARCHIVE}
          tar --use-compress-program=unzstd -xf ${SDK_ARCHIVE}
          mv ${SDK_DIRNAME} openwrt-sdk

      - name: Replace luci feed with ImmortalWrt version
        working-directory: openwrt-sdk
        run: |
          # 注释掉 SDK 自带的 luci feed
          sed -i 's|^src-git luci.*|# &|' feeds.conf.default
          # 添加 ImmortalWrt luci 和 packages
          echo "src-git luci https://github.com/immortalwrt/luci.git;${{ github.event.inputs.luci_ref }}" >> feeds.conf.default
          echo "src-git immortalwrt_packages https://github.com/immortalwrt/packages.git;${{ github.event.inputs.packages_ref }}" >> feeds.conf.default

      - name: Update feeds and defconfig
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build ddns-go packages
        working-directory: openwrt-sdk
        run: |
          # 先编译 Go 工具链
          make package/golang/host/compile V=s
          # 编译 ddns-go 及 LuCI 前端
          make package/ddns-go/compile V=s | tee build-ddns-go.log
          make package/luci-app-ddns-go/compile V=s | tee -a build-ddns-go.log

      - name: Collect built packages
        id: collect
        working-directory: openwrt-sdk
        run: |
          mkdir -p ../release-ipks
          find bin/packages/${ARCH_DIR} -type f -name 'ddns-go*.ipk' -exec cp {} ../release-ipks/ \;
          find bin/packages/${ARCH_DIR} -type f -name 'luci-app-ddns-go*.ipk' -exec cp {} ../release-ipks/ \;
          find bin/packages/${ARCH_DIR} -type f -name 'luci-i18n-ddns-go-zh-cn*.ipk' -exec cp {} ../release-ipks/ \;
          echo "release_tag=ddns-go-${{ env.OPENWRT_VERSION }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt-sdk/build-ddns-go.log

      - name: Upload artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: ddns-go-x86_64-ipk
          path: release-ipks/*.ipk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.collect.outputs.release_tag }}
          name: DDNS-Go Suite for OpenWrt ${{ env.OPENWRT_VERSION }} (${{ github.sha }})
          draft: false
          prerelease: false
          files: release-ipks/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
