name: Build ImmortalWrt Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git wget unzip \
            file libssl-dev python3 zstd qemu-utils genisoimage grub2

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
          tar -I zstd -xf immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
          mv immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64 imagebuilder

      - name: Prepare custom files
        run: |
          mkdir -p imagebuilder/files/etc/uci-defaults
          cp uci-custom imagebuilder/files/etc/uci-defaults/99-custom-network
          mkdir -p imagebuilder/packages
          cp packages/*.ipk imagebuilder/packages/ || true

      - name: Build firmware
        working-directory: imagebuilder
        run: |
          # 读取 packages.list 并拼接成参数
          PKGS=$(tr '\n' ' ' < ../packages.list)
          make image \
            PACKAGES="$PKGS" \
            FILES="files" \
            EXTRA_IMAGE_NAME="custom"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: imagebuilder/bin/targets/x86/64/*

      - name: Release firmware
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: imagebuilder/bin/targets/x86/64/*
