name: Build OpenClash for Chaos Calmer SDK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget curl unzip \
            libncurses5-dev zlib1g-dev gawk gettext libssl-dev xsltproc \
            rsync file

      - name: Download OpenWrt SDK
        run: |
          curl -SLk --connect-timeout 30 --retry 2 \
            "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" \
            -o /tmp/SDK.tar.bz2
          tar -xjf /tmp/SDK.tar.bz2 -C $GITHUB_WORKSPACE
          mv $GITHUB_WORKSPACE/OpenWrt-SDK-15.05.1-* $GITHUB_WORKSPACE/sdk

      - name: Clone luci-app-openclash
        run: |
          mkdir -p sdk/package/luci-app-openclash
          cd sdk/package/luci-app-openclash
          git init
          git remote add -f origin https://github.com/vernesong/OpenClash.git
          git config core.sparseCheckout true
          echo "luci-app-openclash" >> .git/info/sparse-checkout
          git pull --depth 1 origin master
          git branch --set-upstream-to=origin/master master

      - name: Build po2lmo
        run: |
          cd sdk/package/luci-app-openclash/luci-app-openclash/tools/po2lmo
          make
          sudo make install

      - name: Compile luci-app-openclash
        run: |
          cd sdk
          make package/luci-app-openclash/luci-app-openclash/compile V=99

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-openclash-ipk
          path: sdk/bin/ar71xx/packages/base/luci-app-openclash_*_all.ipk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: sdk/bin/ar71xx/packages/base/luci-app-openclash_*_all.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
