name: Build OpenClash Suite (x86-64)

on:
  workflow_dispatch:
    inputs:
      openclash_ref:
        description: 'OpenClash commit/branch/tag to build (default: master)'
        required: false
        default: 'master'

jobs:
  build-openclash-suite:
    runs-on: ubuntu-22.04

    env:
      OPENWRT_VERSION: 24.10.3
      TARGET_DIR: x86/64
      ARCH_DIR: x86_64
      SDK_DIRNAME: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64
      SDK_ARCHIVE: openwrt-sdk-24.10.3-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    steps:
      - name: Free disk space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          echo "After cleanup:"
          df -h

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget zstd

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET_DIR}/${SDK_ARCHIVE}
          tar --use-compress-program=unzstd -xf ${SDK_ARCHIVE}
          mv ${SDK_DIRNAME} openwrt-sdk

      - name: Fetch OpenClash source (shallow clone)
        run: |
          git clone --depth=1 https://github.com/vernesong/OpenClash.git src-openclash
          cd src-openclash
          git checkout "${{ github.event.inputs.openclash_ref }}" || true

      - name: Place OpenClash package into SDK
        run: |
          cp -r src-openclash/luci-app-openclash openwrt-sdk/package/openclash

      - name: Update feeds and defconfig
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build OpenClash and dependencies
        working-directory: openwrt-sdk
        run: |
          make package/openclash/compile -j$(nproc) V=s | tee build-openclash.log
          make package/luci-app-openclash/compile -j$(nproc) V=s | tee -a build-openclash.log

      - name: Collect built packages
        id: collect
        working-directory: openwrt-sdk
        run: |
          mkdir -p ../release-ipks
          find bin/packages/${ARCH_DIR} -type f -name 'luci-app-openclash*.ipk' -exec cp {} ../release-ipks/ \;
          find bin/packages/${ARCH_DIR} -type f -name 'luci-i18n-openclash-*.ipk' -exec cp {} ../release-ipks/ \;
          echo "release_tag=openclash-${{ env.OPENWRT_VERSION }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt-sdk/build-openclash.log

      - name: Upload artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: openclash-x86_64-ipk
          path: release-ipks/*.ipk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.collect.outputs.release_tag }}
          name: OpenClash Suite for OpenWrt ${{ env.OPENWRT_VERSION }} (${{ github.sha }})
          draft: false
          prerelease: false
          files: release-ipks/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
