name: Cleanup All Completed Workflow Runs

on:
  # schedule:
  #   - cron: "0 3 * * *"   # 已注释：每天凌晨 3 点执行
  workflow_dispatch:         # 仅支持手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all completed workflow runs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.paginate(
              github.rest.actions.listWorkflowRunsForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
              }
            );

            for (const run of runs) {
              if (run.status === "completed") {
                console.log(`Deleting run ${run.id} from ${run.created_at}`);
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                });
              }
            }
